---
- name: Setup a new raspberry for an Axiacore door

  hosts: raspberry

  remote_user: pi

  become: true

  roles:
   - raspberry

  post_tasks:
    - name: Restart server
      become: true
      command: reboot
      async: 0
      poll: 0
      ignore_errors: true
