---
- name: Setup a new raspberry for an AxiaCore Door

  hosts: raspberry

  remote_user: pi

  become: true

  roles:
   - raspberry

  post_tasks:
    - name: Restart server
      become: true
      command: reboot
      async: 0
      poll: 0
      ignore_errors: true

    - name: Wait for server
      local_action:
        module: wait_for
          host={{ inventory_hostname }}
          port=22
          delay=1
          timeout=300
