- name: Enable locale
  lineinfile:
    dest: /etc/locale.gen
    state: present
    regexp: '^# en_US.UTF-8 UTF-8'
    line: 'en_US.UTF-8 UTF-8'

- name: Generate locale
  command: locale-gen en_US.UTF-8

- name: Install the wifi driver
  script: bin/install-8188eu

- name: Set the wifi credentials
  template:
    src: wpa_supplicant.conf.j2
    dest: /etc/wpa_supplicant/wpa_supplicant.conf
    mode: "u=rw,g=,o="

- name: Copy keepalive script
  copy:
    src: bin/keepalivewifi
    dest: /usr/local/bin/keepalivewifi
    mode: "u=rwx,g=rx,o=rx"

- name: Add keepalive to cron
  cron:
    name: "keepalive"
    minute: "*"
    job: "root /usr/local/bin/keepalivewifi"

- name: Add mopidy sources
  command: wget -q -O /etc/apt/sources.list.d/mopidy.list https://apt.mopidy.com/mopidy.list

- name: Add mopidy keys
  command: apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 78FD980E271D2943

- name: Install packages
  apt:
    pkg: "{{ item }}"
    state: installed
    update_cache: yes
  with_items:
    - python-dev
    - python-pip
    - gstreamer0.10-plugins-bad
    - mopidy
    - nginx-extras

- name: Install mopidy extensions
  command: pip install Mopidy-Youtube Mopidy-MusicBox-Webclient

- name: Set mopidfy configuration
  template:
    src: mopidy.conf.j2
    dest: /etc/mopidy/mopidy.conf

- name: Start mopidy service on boot
  command: update-rc.d mopidy enable

- name: Copy open-door script
  copy:
    src: bin/open-door
    dest: /usr/local/bin/open-door
    mode: "u=rwx,g=rx,o=rx"

- name: Allow any user to run the script as root
  lineinfile: >
      dest=/etc/sudoers
      line='www-data ALL=(root) NOPASSWD: /usr/local/bin/open-door'

- name: Set nginx configuration
  template: src=default.j2 dest=/etc/nginx/sites-enabled/default
