- name: Install packages
  apt:
    pkg: "{{ item }}"
    state: installed
    update_cache: yes
  with_items:
    - mplayer
    - python-pip
    - nginx-extras

- name: Allow www-data user to run mplayer
  lineinfile: >
      dest=/etc/sudoers
      line='www-data ALL=(root) NOPASSWD: /usr/bin/mplayer'

- name: Copy open-door script
  copy:
    src: bin/open-door
    dest: /usr/local/bin/open-door
    mode: "u=rwx,g=rx,o=rx"

- name: Allow www-data user to run open-door
  lineinfile: >
      dest=/etc/sudoers
      line='www-data ALL=(root) NOPASSWD: /usr/local/bin/open-door'

- name: Set nginx site configuration
  template: src=default.j2 dest=/etc/nginx/sites-enabled/default
